name: Unzip Files

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
      
    - name: Unzip file
      run: unzip -o callow3.zip -d ./
